[lumina]
# server display name; appears in IDA output window
server_name = "lumen"

# Each listener accepts either TLS or plain TCP. TLS is enabled for a listener
# by adding its `tls` table; omit it to accept plain TCP.
[[lumina.listeners]]
bind_addr = "0.0.0.0:1234"

# Example of an additional TLS listener:
# [[lumina.listeners]]
# bind_addr = "0.0.0.0:1235"
# [lumina.listeners.tls]
# Specify the server's PKCS#12 certificate. Clients connecting to this listener
# must match this certificate. Set `PKCSPASSWD` if the certificate is password-protected.
# server_cert = "path/to/server_crt"

# Allow clients to delete metadata from the database?
allow_deletes = false
# How many function histories should we return? 0=Disabled.
get_history_limit = 50


[database]
# Specifies a postgresql connection string. All variables can be found here: https://docs.rs/tokio-postgres/0.6.0/tokio_postgres/config/struct.Config.html
connection_info = "postgres://postgres:1@127.0.0.1/postgres"
# Sets if the database connection should be made using TLS.
use_tls = false
# If the database requires a secure connection, paths to server-ca and client-id certificates can be set here:
server_ca = "db_ca.pem"
client_id = "db_id.p12"

# comment out this section to disable api server
# api server allows to query the database for comments by file or function hash.
[api_server]
bind_addr = "0.0.0.0:8082"
