[package]
name = "lumen"
description = "lumen server"
version = "0.2.0"
authors = ["Naim A. <naim@abda.nl>"]
edition = "2021"
publish = false

[dependencies]
common = { path = "../common" }
tokio = { version = "1.39", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
clap = "4.5"
tokio-native-tls = "0.3"
native-tls = { version = "0.2" }
warp = "0.3"
prometheus-client = "0.22"
